spring.application.name=studyRecord_app

spring.datasource.url=jdbc:postgresql://localhost:5432/study_record
spring.datasource.username=fuarahomare
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=false